Startup files
gooey-synths/audio_dev_kit_bsp pull request #12
Opened 2022-10-24 22:43 UTC by alexpratte16

Added startup files
core_cm7.h and stm32h750xx.h are straight from CMSIS.
Enables floating point

2022-10-25 00:01 UTC, carllb approved these changes

2022-10-26 22:56 UTC, Christopher-Finelli commented on base/src/init/startup.c
> +extern uint32_t _sstack; //< Start of stack
pick one section or not section

2022-10-26 22:57 UTC, Christopher-Finelli commented on base/src/init/startup.c
> +extern uint32_t _sstack; //< Start of stack
for stacks

2022-10-26 23:02 UTC, Christopher-Finelli commented on base/src/init/startup.c
> +    ISR_NOT_IMPL, /* Tamper and TimeStamps through the EXT */
EXTI???

2022-10-26 23:02 UTC, Christopher-Finelli commented on base/src/init/startup.c
> +    ISR_NOT_IMPL, /* Tamper and TimeStamps through the EXT */
should the ext be exti

2022-10-26 23:44 UTC, Christopher-Finelli requested changes
A few typos that i commented on

2022-11-28 22:26 UTC, Christopher-Finelli approved these changes

2022-11-30 17:57 UTC, merged